import '@radix-ui/themes/styles.css';
import './globals.scss';
import './theme-config.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavBar from './NavBar';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import NextAuthProvider from './auth/NextAuthProvider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <NextAuthProvider>
          <Theme accentColor="violet">
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </NextAuthProvider>
      </body>
    </html>
  );
}
